ads:
  picture-quality-score:
    HD: 20
    SD: 10
  no-picture-penalty: -10
  description:
    keywords:
      keywords:
        - Luminoso
        - Nuevo
        - Céntrico
        - Reformado
        - Ático
      score: 5
    descriptive:
      score: 5
    word-ranges:
      FLAT:
        - min: 20
          max: 49
          score: 10
        - min: 50
          max: 500
          score: 30
      CHALET:
        - min: 50
          max: 500
          score: 20
  complete:
    score: 40
  score-bounds:
    max: 100
    min: 0
    relevant-min-score: 40
